dbt-labs/dbt-server

.changes/unreleased/Under the Hood-20221129-141225.yaml, .github/actions/docker-build-publish/action.yml, .github/actions/notify-dbt-runtime/action.yml, .github/actions/registry-login-action/action.yml, .github/workflows/main.yml
This PR adds github actions for dbt-server
=> Add GitHub actions

.changes/unreleased/Fixes-20221208-125119.yaml, dbt_server/views.py
=> add profile as optional sqlconfig arg

.changes/unreleased/Fixes-20221208-130454.yaml, dbt_server/server.py
=> Adds missing field

.github/workflows/main.yml
=> Add 1.4.0-pre to the build matrix

dbt_server/state.py, dbt_server/views.py
Moves the `invoke_dbt` logic to a method on the `StateController` to make use of cacheing. Logic could probably be further separated into the service for cleanliness, I went with the simplest change for now.
=> Core integration updates

.changes/unreleased/Under the Hood-20221205-130706.yaml, .github/actions/notify-dbt-runtime/action.yml, .github/workflows/main.yml
https://dbtlabs.atlassian.net/browse/INFRA-1411
This is a:
This is to add cicd for runtime to the Sydney MT instance.
=> INFRA-1411 Add cicd for AU.

README.md
=> touch README to trigger workflow

dev-requirements.txt, tests/e2e/helpers.py, tests/e2e/test_compilation.py, tests/e2e/test_state.py, tests/e2e/test_views.py, tests/integration/test_cache.py
This is a:
Fix tests.
- Replace old env setup helper function(buggy) with DbtCoreTestBase. The idea is that I noticed lot's of tests will set dbt core envs and cleanup in tearDown, so I refactor it out of test class.
- test_compilation.py, adopts new DbtCoreTestBase to fix bug. It requires to install dbt-postgres, I added this dependency in dev requirements.
- test_state.py, adopts new DbtCoreTestBase to fix bug,
- test_views.py, adopts new DbtCoreTestBase to fix bug.
- test_cache.py, add get_latest_project_path patch to ensure tests are not related to local cache files.
=> Fix tests.

.changes/unreleased/Under the Hood-20230222-124703.yaml, .github/actions/docker-build-publish/action.yml, .github/actions/registry-login-action/action.yml, .github/workflows/main.yml
This is a:
Makes changes to build dbt-core <=1.4.0-latest images from the 0.1.latest branch
=> Build images from 0.1.latest

README.md
=> Touch to redeploy

.github/workflows/main.yml
This is a:
Simplifies github action logic
=> Removes conditionals in github actions

.changes/unreleased/Under the Hood-20230303-060944.yaml, .github/actions/docker-build-publish/action.yml, .github/actions/registry-login-action/action.yml, .github/workflows/main.yml
This is a:
Adds dev registry keys so that images will be pushed to the dev ECR repos
=> Adds dev registry keys

bash/ubuntu-setup-redis.sh
This is a:
Redis installation bash script, I have tested in local ubuntu docker image.
=> [CLOUDEXEC-784] Add ubuntu redis installation bash.

Dockerfile
This is a:
Copy dbt worker directory in dockerfile.
=> Copy dbt worker

dbt_server/services/dbt_service.py, dbt_worker/tasks.py
This is a:
Quick fix in case existing SL pods hit an error-- I've seen a case now where dbt returns `success: FALSE, exception: None`. I'm going to raise this to the core team, but for now I don't want any pods that are already live getting into a bad state.
=> Adds error handling for missing dbt-core exceptions

.changes/unreleased/Features-20230428-090955.yaml, .github/workflows/main.yml
This is a:
Adds latest core release
=> Adds core 1.5.0-latest

dbt_worker/tasks.py
This is a:
Adds a retry and SIGKILL after attempted SIGINT-- added at the suggestion of the core team, as there is apparently a core bug that causes SIGINT timeouts sometimes
=> Retry sigint

.changes/unreleased/Features-20230517-142113.yaml, .github/workflows/main.yml, Dockerfile, dev-requirements.txt, requirements.txt
This is a:
Adds builds for databricks and spark images to github actions. This should not be merged until this PR has been approved and merged: https://github.com/dbt-labs/dbt-cloud-infra-terraform/pull/1122
=> Adds builds for databricks, trino and spark images

.changes/unreleased/Features-20230523-150756.yaml, .github/workflows/main.yml
=> Adds dbt core v 1.6.0b1

bash/ubuntu-run.sh
This is a:
Fixes bug in bash script gunicorn startup command
=> Fix gunicorn command typo

dbt_worker/tasks.py
This is a:
removes extra invoke!
=> removes extra invoke

.changes/unreleased/Features-20230721-162224.yaml, dbt_server/tracer.py
This is a:
This PR backports the changes to the APM client added in #243 to `0.1.latest`
=> Backport APM changes from #243

dbt_server/services/dbt_service.py
One compile at a time given that the Gunicorn workers actually share the same manifest object
=> add a process lock for compile
