dbt-labs/dbt-server

- .changes/unreleased/Fixes-20221129-082728.yaml
- dbt_server/server.py
- dbt_server/state.py
- dbt_server/views.py
- tests/integration/test_compile.py
This is a:
Passes args through parse, sql compile and preview endpoints to the StateController; updates the StateController methods to accept args to be passed to parse function in lib.py that already accepts args.
This is part of a larger effort to accept custom targets for the Semantic Layer, but this PR does not include breaking changes and can be merged before the other PRs if necessary.
**Other PRS**
- [runtime-gateway](https://github.com/dbt-labs/runtime-gateway/pull/186)
- [workspace-controller](https://github.com/dbt-labs/workspace-controller/pull/96)
- [dbt-cloud](https://github.com/dbt-labs/dbt-cloud/pull/5949)
- [cloud-ui](https://github.com/dbt-labs/cloud-ui/pull/921)
- …
> Passes target name through StateController for each config creation

- dbt_server/services/dbt_service.py
- dbt_server/services/filesystem_service.py
- dbt_server/state.py
- dbt_server/views.py
This is a:
Adds partial parsing to feature branch. This currently hardcodes the target folder as `target`-- this folder name is configurable in core via flag or env var, but we don't currently accept that flag on `push` and would need to do so to allow this. 
Partial parsing is likely going to get easier/smoother with the click api work-- this is more of a POC that we can do partial parsing.
> Support partial parsing

- .changes/unreleased/Under the Hood-20221221-112702.yaml
- dev-requirements.txt
- requirements.txt
This is a:
Right now - on the current version of FastAPI that dbt-server uses - when an error occurs after a request has been made to an async endpoint, the actual error message gets obfuscated by an underlying dependency that FastAPI uses, Starlette. Here's an example of the issue we're seeing where the actual error gets overwritten by Starlette:
```
2022-12-08 12:07:53,666 - [47226] asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-4' coro=<BaseHTTPMiddleware.call_next.<locals>.coro() done, defined at /Users/racheldaniel/.pyenv/versions/3.8.13/envs/dbt-server-env/lib/python3.8/site-packages/starlette/middleware/base.py:36> exception=RuntimeError('Caught handled …
```
> Upgrade FastAPI version in requirements.txt and add httpx to dev-requirements.txt to resolve error handling issue with underlying FastAPI dependency

- dbt_server/crud.py
- dbt_server/helpers.py
- dbt_server/models.py
- dbt_server/server.py
- dbt_server/services/dbt_service.py
- dbt_server/state.py
- dbt_server/views.py
This is a:
Tiny fix-- async endpoint should not default to user, that was old dbt-server logic. This helper func should also change eventually, as we won't be handling `args` the same way (if the profile flag is included in the command, it will work the way we are currently using `args` in that helper func)
Also adds a `checkfirst` flag to db creation, as every once in a while the client sees a `sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table tasks already exists` .
> Fix profile for async endpoint

- .changes/unreleased/Features-20230206-120426.yaml
- dbt_server/crud.py
- dbt_server/services/dbt_service.py
- dbt_server/state.py
- dbt_server/views.py
- dev-requirements.txt
- requirements.txt
- tests/e2e/test_state.py
- tests/e2e/test_views.py
This is a:
- Add a new method to update task status and remove the individual status update methods. This allows us to generically call it upstream
- Accept a callback url as part of the async endpoint request
- Every time task status is updated, send a post request to the callback url with the status. The call will be retried a max of 5 times
- Return the state ID as part of the async endpoint response. This is needed in workspace controller to find the working directory
- Class rename
> Add task status callback

- dbt_server/database.py
- dbt_server/services/dbt_service.py
- dbt_server/services/filesystem_service.py
- dbt_server/state.py
This is a:
When this was tested in the IDE, the server's attempts to write to the app root threw permissions errors. This PR ensures that:
- The sqlite db file is written to the working_dir instead of the app root
- dbt Commands are run from the project root, as the target path is not currently fully customizeable through the core API, and this ensures that the target dir defaults to the project root instead of app root
> Control server write locations

- dbt_server/views.py
This is a:
We have a need to manage task IDs in services that use `dbt-server`, so this PR adds support for accepting a task ID as part of the request and using that for the lifecycle of a task.
> Support upstream task IDs

- dbt_server/services/dbt_service.py
This is a:
This bug is caught while I'm testing smoke test. The behavior is 
- I create jaffle shop at temp dir.
- Parse + testing...
- Delete jaffle shop.
- Create another jaffle shop at a different temp dir.
- Parse(error)
Spent some times digging into this, I think it's because async end points change the working directory while because I send the wrong commands and exception is thrown, os.chdir(dbt_server_root) won't be executed.
Hence I use finally to ensure it would always be rolled back.
> Fix bug of not chdir back

- .github/actions/docker-build-publish/action.yml
- .github/actions/registry-login-action/action.yml
- .github/workflows/main.yml
This is a:
Removal of these keys caused an ImagePullbackoff error in prod, these were removed for testing and accidentally not returned
> [Bug] production key removal

- .changes/unreleased/Under the Hood-20230227-113905.yaml
- .github/workflows/main.yml
This is a:
Tailors the test actions in our github actions to the branch, rather than using conditionals
> Removes conditional on test, tailors to branch

- .changes/unreleased/Fixes-20230228-180450.yaml
- dbt_server/services/dbt_service.py
- dbt_server/services/filesystem_service.py
- tests/integration/test_cache.py
- tests/integration/test_compile.py
- tests/unit/test_filesystem.py
Prior to performing a `parse`, ensure that local deps are symlinked in `dbt_packages`
This change has been tested on projects with and without `packages.yml`
This is a:
> Prior to performing a parse, ensure that local deps are symlinked in dbt_packages

- .github/workflows/main.yml
This is a:
Today pip install "https://github.com/dbt-labs/dbt-snowflake/archive/HEAD.tar.gz#egg=dbt-snowflake" failure cause all CI/CD tests and snowflake image build test are failed.
Asked adaptor team and they suggest to use git+https... to install head package.
Tested locally.
(.venv2) ➜  dbt-server git:(dichen/dev_4) ✗ dbt --version
Core:
- installed: 1.5.0-b2
- latest:    1.4.4    - Ahead of latest version!
Plugins:
- bigquery:  1.5.0b1 - Ahead of latest version!
- snowflake: 1.5.0b1 - Ahead of latest version!
- redshift:  1.5.0b1 - Ahead of latest version!
- postgres:  1.5.0b2 - Ahead of latest version!
-
> Use git+ to install package.

- .changes/unreleased/Features-20230324-103931.yaml
- dbt_server/server.py
- dbt_server/services/dbt_service.py
- dbt_server/services/filesystem_service.py
- dbt_server/services/filesystem_service_test.py
- dbt_server/services/task_service.py
- dbt_server/state.py
- dbt_server/views.py
This is a:
Adds a hack to allow partial parsing-- on push, if previous state exists, copy the partial parsing file from that state to new state folder so that it can be accessed on parse
Also copies over some of the new filesystem service tests from 0.2.0
> Adds partial parsing and tests

- dbt_server/services/filesystem_service.py
- dbt_server/services/filesystem_service_test.py
- dbt_server/state.py
- dbt_server/views.py
- tests/integration/test_cache.py
- tests/unit/test_filesystem.py
This is a:
Recently a bug was introduced where relative paths would result in incorrect nested artifacts paths like this: `../working-dir/state-{state_id}/working-dir/state-{state_id}/{task_id}`. Making paths absolute corrects this-- unclear whether this has affected prod, but it would only be for users on beta versions of core.
Also adds some logic to the StateController to allow the `/async/dbt` endpoint to be called with a `project_path`, without first calling `/parse`
> [BUG] Make paths absolute

- dbt_server/services/dbt_service.py
- dbt_server/services/filesystem_service.py
- dbt_server/services/filesystem_service_test.py
- dbt_server/state.py
- dbt_server/state_test.py
This is a:
This was removed in server 0.1.0 and I want to remove it here for cleanup and to close out this ticket. The copy that was here (and the function written for it) were extraneous and resulted in multiple `partial_parse.msgpack` files being written out.
> Removes duplication of partial parse

- dbt_server/views.py
- dbt_server/views_test.py
- dbt_worker/tasks.py
- dbt_worker/tasks_test.py
This is a:
Until core has completed [this bug ticket](https://github.com/dbt-labs/dbt-core/issues/6985), we need to intentionally chdir to the project root before running a dbt command, then chdir back to the server root afterward. This compensates for core 1. Writing an empty `dbt_packages` folder to wherever the command is being called (in our case, the server root, which we do not want)
2. Changing directories to the project root for a deps and not changing back, which prevents the server from specifying a task artifacts/project state folder that is relative to the server code path.
> Adds chdir before and after dbt run

- Dockerfile
- bash/celeryd.sh
- bash/ubuntu-run.sh
- configs/celeryd
- dbt_server/flags.py
- dbt_server/logging.py
- dbt_server/server.py
- dbt_worker/tasks.py
- dbt_worker/tasks_test.py
This is a:
This copies env vars from the kubernetes container and sources them where the celery worker can access them. Also includes a minor change to the callback for core logs-- this callback is not currently helping us, but the Event type structure changed so I'm keeping at least that work for now, with a note to make it work.
> Give celery access to env vars

- dbt_worker/tasks.py
This is a:
In the latest core commit, the tuple that was returned from `dbtRunner.invoke()` was changed to a DbtRunnerResult object. We don't do anything with this value anyway, keeping a single underscore as it will cover both cases
> Fixes invoke return type to allow class and tuple

- dbt_server/server.py
This is a:
Adds error handling-- this error handling has been on `main` for a while and was just removed with all of the other sqlalchemy code, but was never backported to `0.1.latest` as this error has never been a problem in prod, and the sqlite db isn't used in prod. It's unclear why this is just now an issue, but this is very low risk to add while we figure that out.
> Adds error handling for sqlalchemy exceptions

- dbt_server/services/dbt_service.py
- dbt_worker/tasks.py
This is a:
Currently dbt-core will return dbtRunnerResult(success=False, exception=None, ...) when a task failed gracefully, but dbt-server always expects an exception or sets state to SUCCESS. 
This PR updates task state in redis to `FAILURE` even if there is no exception data from core, and removes unnecessary loglines for acceptable core error state.
> Implements handled dbt error case

- .changes/unreleased/Under the Hood-20230504-114534.yaml
- .github/_README.md
- .github/actions/docker-build-publish/action.yml
- .github/actions/registry-login-action/action.yml
- .github/workflows/main.yml
- tests/e2e/fixtures/jaffle_shop/dbt_packages/dbt_meta_testing/.github/workflows/integration_tests.yml
This is a:
resolves #222 
Update versions of used Github Actions ahead of:
[node12 deprecation](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) (Summer 2023)
[set-output deprecation](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) (fully disabled on 31st May 2023)
> update used gh actions ahead of set-output, node12 deprecation

- Dockerfile
- bash/liveliness.sh
- dbt_worker/app.py
- dbt_worker/tasks.py
This is a:
Adds liveliness tracking using celery signals and a shell script that can be used to check readiness and liveliness. This PR is in conjunction with [dbt-cloud PR #7344](https://github.com/dbt-labs/dbt-cloud/pull/7344).
The bash script:
1. Sends an http request to the `/ready` endpoint of dbt-server to make sure server itself is up
2. Makes sure the broker can be accessed via the command `redis-cli` and sending a ping
3. Verifies that a file `/tmp/worker_heartbeat` exists and has been touched in the last 10 seconds (this `touch` command is executed once the worker is ready, then again as a part of the celery worker's steps, making use of celery signals)
These steps should confirm that the …
> Add health checks for server processes

- .changes/unreleased/Features-20230710-140525.yaml
- dbt_server/tracer.py
- tests/e2e/test_compilation.py
This is a:
This PR adds a new environment variable `PROFILING_ENABLED` to separately configure profiling from APM.
> Add PROFILING_ENABLED env var

- dbt_server/services/dbt_service.py
> remove any leftover inline node before compile
